===============================================================PANDAS=============================================================

why
-> import datasets
-> data cleaning
-> size mutability
-> reshaping and pivoting datasets
-> efficient and extraction
-> statistical anlysis

1) seris - 1d(homoenous array)-size is immutable
2) data frames - 2d (heteroeneous)- size mutable
functions
-> describe
-> info
-> head
-> tail
-> shape

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
-----------SERIES-------------------------

In [2]:
import pandas as pd

In [6]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
s.values

array([10, 20, 30, 40, 50], dtype=int64)

In [8]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
print(s.name)

None

In [13]:
s.names='numbers'

INDEXGING

In [14]:
s[0]

10

In [15]:
s[2:4]

2    30
3    40
dtype: int64

In [16]:
s.iloc[3] #location based indexing

40

In [17]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
dtype: int64

In [19]:
index=['apple','banana','orange','straw','grapes']
s.index=index
s

apple     10
banana    20
orange    30
straw     40
grapes    50
dtype: int64

In [20]:
s['straw']

40

In [21]:
s.iloc[3]

40

In [22]:
#loc -> label based indexing

s.loc['grapes']

50

s['orange':'grapes']
s

In [32]:
fruits_pro={
    'avacado':2.0,
    'guava':2.6,
    'orange':0.9,
    'banana':1.1,
    'apple':0.3,
    'straw':1.0,
    'mango':0.8,
}

In [36]:
s2 = pd.Series(fruits_pro,name='protein')
s2

avacado    2.0
guava      2.6
orange     0.9
banana     1.1
apple      0.3
straw      1.0
mango      0.8
Name: protein, dtype: float64

In [38]:
#conditinal selection
s2[s2>1]

avacado    2.0
guava      2.6
banana     1.1
Name: protein, dtype: float64

In [43]:
#loical operators and not or

# and = true & true == true
# or = true & false == true any one
# not != 

s2[(s2>0.5) & (s2<2)]

orange    0.9
banana    1.1
straw     1.0
mango     0.8
Name: protein, dtype: float64

In [44]:
s2[(s2>0.5) | (s2<2)]

avacado    2.0
guava      2.6
orange     0.9
banana     1.1
apple      0.3
straw      1.0
mango      0.8
Name: protein, dtype: float64

In [45]:
#Modifing te series
s2['mango']=2.9
s2

avacado    2.0
guava      2.6
orange     0.9
banana     1.1
apple      0.3
straw      1.0
mango      2.9
Name: protein, dtype: float64

In [ ]:
------------DATAFRAMES---------------

In [55]:
data = {
    'name': ['Rahul','Anita','Suresh','Priya','Kiran'],
    'age':[23,45,53,89,43,],
    'department':['Sales','HR','IT','Finance','Service'],
     'salary':[70000,45000,78000,80000,30000]
         }

In [56]:
data

{'name': ['Rahul', 'Anita', 'Suresh', 'Priya', 'Kiran'],
 'age': [23, 45, 53, 89, 43],
 'department': ['Sales', 'HR', 'IT', 'Finance', 'Service'],
 'salary': [70000, 45000, 78000, 80000, 30000]}

In [57]:
df = pd.DataFrame(data)
df

     name  age department  salary
0   Rahul   23      Sales   70000
1   Anita   45         HR   45000
2  Suresh   53         IT   78000
3   Priya   89    Finance   80000
4   Kiran   43    Service   30000

In [59]:
df.head(2)

    name  age department  salary
0  Rahul   23      Sales   70000
1  Anita   45         HR   45000

In [60]:
df.tail(2)

    name  age department  salary
3  Priya   89    Finance   80000
4  Kiran   43    Service   30000

In [61]:
df.iloc[1:3]

     name  age department  salary
1   Anita   45         HR   45000
2  Suresh   53         IT   78000

In [66]:
df.iloc[1:2, [2,3]]

  department  salary
1         HR   45000

In [68]:
df[['age','department']]

   age department
0   23      Sales
1   45         HR
2   53         IT
3   89    Finance
4   43    Service

In [70]:
df.shape

(5, 4)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   age         5 non-null      int64
 2   department  5 non-null      object
 3   salary      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

In [74]:
df.describe()

             age        salary
count   5.000000      5.000000
mean   50.600000  60600.000000
std    24.141251  22063.544593
min    23.000000  30000.000000
25%    43.000000  45000.000000
50%    45.000000  70000.000000
75%    53.000000  78000.000000
max    89.000000  80000.000000

In [90]:
#broadcasting

df['salary']=df['salary'] + 5000
df['salary']

0    1750000015500
1    1125000015500
2    1950000015500
3    2000000015500
4     750000015500
Name: salary, dtype: int64

In [84]:
df.rename(columns ={'department': 'dept'},inplace=True)
df

     name  age     dept         salary
0   Rahul   23    Sales  1750000015000
1   Anita   45       HR  1125000015000
2  Suresh   53       IT  1950000015000
3   Priya   89  Finance  2000000015000
4   Kiran   43  Service   750000015000

In [85]:
df['dept'].unique() #value_count() : count like groupby

array(['Sales', 'HR', 'IT', 'Finance', 'Service'], dtype=object)

In [ ]:
----------Data Cleaning--------

In [95]:
df.isnull()
df.dropna()
df.dropna(how='any') # any row that had null values
df.fillna(0)
df['age'].fillna(df['age'].mean()) # filling with mean
df['salary'].fillna(df['salary'].median())

0    1750000015500
1    1125000015500
2    1950000015500
3    2000000015500
4     750000015500
Name: salary, dtype: int64

In [101]:
#forwad fill and bacwardfill
# upward and backward data wil be filled in na value
# df['age'].fillna(method='ffill')
# df['age'].fillna(method='bfill')

In [103]:
df['name'].replace('Rahul','hari')

0      hari
1     Anita
2    Suresh
3     Priya
4     Kiran
Name: name, dtype: object

In [107]:
#DEleaing with duplicate data
df_dup=df[df.duplicated()] //not duplictas in data
df=df.dropduplicate()

In [113]:
#invalid values

# df['promoted_salary']=df['promoted_salary'].apply(lambda x : x/10 if x >60000 else x)

In [115]:
# name='alice hari'
# df[['fn','ln']]=df['name'].str.split('_') not having column

In [117]:
#apply and lamda
df['age']=df['age'].apply(lambda x : x/2)
df

     name    age     dept         salary
0   Rahul   5.75    Sales  1750000015500
1   Anita  11.25       HR  1125000015500
2  Suresh  13.25       IT  1950000015500
3   Priya  22.25  Finance  2000000015500
4   Kiran  10.75  Service   750000015500

In [ ]:
---------JOINS----------------

In [119]:
# PD.CONCAT([df,d2])

In [122]:
# importing file
data = pd.read_csv('orders.csv')

In [123]:
data.head()

   order_id        date      time
0         1  2015-01-01  11:38:36
1         2  2015-01-01  11:57:40
2         3  2015-01-01  12:12:28
3         4  2015-01-01  12:16:31
4         5  2015-01-01  12:21:30

In [125]:
data.shape

(21350, 3)

In [126]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  21350 non-null  int64
 1   date      21350 non-null  object
 2   time      21350 non-null  object
dtypes: int64(1), object(2)
memory usage: 500.5+ KB